### PR TITLE
fix cpd tokens for files with BOM

### LINKED ISSUE #266: fix cpd tokens for files with BOM
Files containing BOM and having tokens on the first line are failing to provide CPD tokens (copy-paste detection) to SonarQube as offsets are incorrect:
```
Caused by: java.lang.IllegalArgumentException: 44 is not a valid line offset for pointer. File [moduleKey=MyKey, relative=src/foo.ts, ...] has 43 character(s) at line 1
```

Reproducing file:
[foo.ts.zip](https://github.com/SonarSource/SonarTS/files/1433808/foo.ts.zip)

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #266

### CODE REVIEW

File: sonarts-core/src/runner/processRequest.ts [hunk 1]
```diff
@@ -34,9 +32,7 @@ export function processRequest(inputString: string): object[] {
     let program = tslint.Linter.createProgram(input.tsconfig);
 
     let output = input.filepaths.map((filepath: string) => {
-        const scriptKind = filepath.endsWith(".tsx") ? ts.ScriptKind.TSX : ts.ScriptKind.TS;
-        const fileContent = fs.readFileSync(filepath, "utf8");
-        const sourceFile = parseString(fileContent, scriptKind);
+        const sourceFile = program.getSourceFile(filepath);
         const output: object = { filepath };
         sensors.forEach(sensor => Object.assign(output, sensor(sourceFile)));
```
Comment (inverno) [inline sonarts-core/src/runner/processRequest.ts]: Bring up logic for missing `sourceFile` from `rules.getIssues`
