### PR TITLE
Rule: Method parameters, caught exceptions and foreach variables' initial values should not be ignored

### LINKED ISSUE #155: Rule: Method parameters, caught exceptions and foreach variables' initial values should not be ignored
Implements [RSPEC-1226](https://jira.sonarsource.com/browse/RSPEC-1226)

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #155

### CODE REVIEW

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+  ) {
+    super(sourceFile, options, program);
+    this.lva = new LiveVariableAnalyzer(this.symbols);
+  }
+
+  protected visitNode(node: ts.Node): void {
+    if (is(node, ...FUNCTION_LIKE)) {
+      const functionLike = node as ts.FunctionLikeDeclaration;
+      const lvaReturn = this.lva.analyzeFunction(functionLike);
+      this.visit(lvaReturn, functionLike.body!, ...functionLike.parameters);
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MINOR Forbidden non null assertion [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS2966)

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+      this.visit(lvaReturn, iterationStatement.statement, (iterationStatement as ts.ForInStatement).initializer);
+    }
+ 
+    super.visitNode(node);
+  }
+  
+  private visit(lvaReturn: LVAReturn, root: ts.Node, ... nodes: ts.Node[]) {
+    const {cfg, blockAvailableReads} = lvaReturn;
+    if (cfg && blockAvailableReads) {
+      const symbolsLiveAtFunctionStart = blockAvailableReads.get(cfg.start)!;
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MINOR Forbidden non null assertion [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS2966)

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+      
+      nodes.forEach(parameter => {
+        descendants(parameter)
+        .filter(descendant => is(descendant, ts.SyntaxKind.Identifier))
+        .forEach(descendant => {
+          const identifier = descendant as ts.Identifier;
+          const symbol = this.getTypeChecker().getSymbolAtLocation(identifier);
+          if (symbol && (symbol.flags == ts.SymbolFlags.BlockScopedVariable || symbol.flags == ts.SymbolFlags.FunctionScopedVariable) && this.isNotUsedElseWhere(symbol, root) && !symbolsLiveAtFunctionStart.has(symbol) && this.symbols.allUsages(symbol).length > 1) {
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MAJOR Exceeds maximum line length of 180 [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS103)
MAJOR == should be === [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440)
MAJOR == should be === [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440)

**Comment by SonarTech** [comment]
SonarQube analysis reported 6 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 3 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [lva.ts#](https://github.com/SonarSource/SonarTS/blob/724ac331621cf7eecdbdf2292e5de4c698304f70/sonarts-core/src/symbols/lva.ts#): file should end with a newline [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS113)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+  ) {
+    super(sourceFile, options, program);
+    this.lva = new LiveVariableAnalyzer(this.symbols);
+  }
+
+  protected visitNode(node: ts.Node): void {
+    if (is(node, ...FUNCTION_LIKE)) {
+      const functionLike = node as ts.FunctionLikeDeclaration;
+      const lvaReturn = this.lva.analyzeFunction(functionLike);
+      this.check(functionLike.body!, lvaReturn, ...functionLike.parameters);
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MINOR Forbidden non null assertion [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS2966)

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+
+    super.visitNode(node);
+  }
+
+  private check(root: ts.Node, lvaReturn?: LVAReturn,  ...nodesToCheck: ts.Node[]) {
+    if (!lvaReturn) {
+      return;
+    }
+    const { cfg, blockAvailableReads } = lvaReturn;
+    const symbolsLiveAtStart = blockAvailableReads.get(cfg.start)!;
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MINOR Forbidden non null assertion [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS2966)

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+      .allUsages(symbol)
+      .every(
+        usage =>
+          usage.is(UsageFlag.DECLARATION) || ancestorsChain(usage.node, ...boundaries).includes(root),
+      );
+  }
+}
+
+function isVariableOrParameter(symbol: ts.Symbol) {
+  return symbol.flags == ts.SymbolFlags.BlockScopedVariable || symbol.flags == ts.SymbolFlags.FunctionScopedVariable;
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MAJOR == should be === [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440)
MAJOR == should be === [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440)

**Comment by SonarTech** [comment]
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+      .allUsages(symbol)
+      .every(
+        usage =>
+          usage.is(UsageFlag.DECLARATION) || ancestorsChain(usage.node, ...boundaries).includes(root),
+      );
+  }
+}
+
+function isVariableOrParameter(symbol: ts.Symbol) {
+  return symbol.flags === ts.SymbolFlags.BlockScopedVariable || symbol.flags === ts.SymbolFlags.FunctionScopedVariable;
```
Comment (SonarTech) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: MAJOR == should be === [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440)
MAJOR == should be === [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440)

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 issues
* ![MINOR][MINOR] 2 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonarts-core/src/symbols/lva.ts [hunk 8]
```diff
@@ -19,22 +19,36 @@
...
+  public analyzeFunction(root: ts.FunctionLikeDeclaration): LVAReturn | undefined {
     if (!is(root.body, ts.SyntaxKind.Block)) {
       return;
     }
-    const cfg = ControlFlowGraph.fromStatements((root.body as ts.Block).statements);
+    return this.analyze(root, (root.body as ts.Block).statements);
+  }
+
+  public analyze(root: ts.Node, statements: ts.Statement[]): LVAReturn | undefined {
+    const cfg = ControlFlowGraph.fromStatements(statements);
```
Comment (inverno) [inline sonarts-core/src/symbols/lva.ts]: Small thing : I think this is a good opportunity to isolate `analyze` from the list of statements and thus build the CFG outside of it, in this case, in `analyzeFunction`.

File: sonarts-core/src/rules/noIgnoredInitialValueRule.ts [hunk 9]
```diff
@@ -0,0 +1,124 @@
...
+    }
+    const { cfg, blockAvailableReads } = lvaReturn;
+    const symbolsLiveAtStart = blockAvailableReads.get(cfg.start)!;
+
+    nodesToCheck.forEach(parameter => {
+      descendants(parameter)
+        .filter(descendant => is(descendant, ts.SyntaxKind.Identifier))
+        .forEach(descendant => {
+          const identifier = descendant as ts.Identifier;
+          const symbol = this.getTypeChecker().getSymbolAtLocation(identifier);
```
Comment (inverno) [inline sonarts-core/src/rules/noIgnoredInitialValueRule.ts]: @vilchik-elena you could use `this.symbols.getUsage(identifier)`, just to avoid using both the symbol table and the type checker
