### PR TITLE
Fix FP S4275/no-accessor-field-mismatch when multiple fields match accessor

### LINKED ISSUE #476: FP S4275/no-accessor-field-mismatch
image
https://github.com/Microsoft/vscode/blob/e5808be148c60f3a9aac27fece7eff1fa21a0264/src/vs/workbench/parts/markers/common/markersModel.ts#L102-L104

### PR DESCRIPTION
**Pull request by saberduck**
Fixes #476

### CODE REVIEW

File: sonarts-core/src/utils/sonarAnalysis.ts [hunk 1]
```diff
@@ -132,8 +132,16 @@ export class SonarIssue extends tslint.RuleFailure {
     return this;
   }
 
-  public addSecondaryLocation(secondaryLocation: IssueLocation): SonarIssue {
-    this.secondaryLocations.push(secondaryLocation);
+  public addSecondaryLocation(node: ts.Node, message: string): SonarIssue;
+  public addSecondaryLocation(secondaryLocation: IssueLocation): SonarIssue;
+  public addSecondaryLocation(): SonarIssue {
+    if (arguments.length == 1) {
```
Comment (SonarTech) [inline sonarts-core/src/utils/sonarAnalysis.ts]: Code Smell Code Smell: == should be === ([typescript:S1440](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=typescript%3AS1440))

[See it in SonarQube](https://next.sonarqube.com/sonarqube/project/issues?id=sonarts&branch=issue-476&issues=AWGdtLPMR7xclXvFe6qP&open=AWGdtLPMR7xclXvFe6qP)

[ISSUE_KEY]: AWGdtLPMR7xclXvFe6qP

**Comment by vilchik-elena** [comment]
@saberduck Not related to this ticket but I found a weird thing in rule desc: `{code}` after noncompliant 
image

**Comment by vilchik-elena** [comment]
Manually tested
