### PR TITLE
Ignore traceResolution property from tsconfig when compiling TS

### LINKED ISSUE #688: traceResolution tsconfig option cause write EPIPE error
**I want to report a bug.**

**SonarTS version:** 1.7.0
**Node.js version:** v8.4.0
**TypeScript version:** 3.0.1

**SonarQube version:** 6.7.3
**SonarScanner version:** 3.1.0.1141-windows

**Reproducer** 

1. Unzip attached sample project [srw_sdk_web_sample.zip](https://github.com/SonarSource/SonarTS/files/2282554/srw_sdk_web_sample.zip) (it is a code sample from the Sabre Red Workspace SDK)
2. Run sonar analysis, e.g.:
```
C:\devel\tools\sonar-scanner-3.1.0.1141-windows\bin\sonar-scanner.bat -Dproject.home=. -Dsonar.projectKey=sample-web -Dsonar.projectName="Sample web" -Dsonar.sources=. -Dsonar.exclusions=**/build/**,**/node_modules/**,**/libs/** -Dsonar.log.level=DEBUG -Dsonar.host.url=http://localhost:9000 -Dsonar.login=PASSWORDHASH
```
3. Error occurring as shown in the logs

I've noticed that `"traceResolution": true` in `tsconfig.json` cause the problem. Removing the option from `tsconfig.json` makes SonarScanner to pass.

**Logs**
```
11:09:06.551 INFO: Sensor SonarTS [typescript]
11:09:06.553 DEBUG: TypeScript compiler is found in this directory C:\devel\projects\srw\web_sample\node_modules
11:09:06.553 DEBUG: It will be used for analysis of typescript files
11:09:06.554 DEBUG: Deploying bundle to c:\devel\projects\srw\web_sample\.scannerwork
11:09:10.214 DEBUG: Checking node version
11:09:10.361 DEBUG: Using Node.js v8.4.0
11:09:10.366 ERROR: No tsconfig.json file found for [file:///C:/devel/projects/srw/web_sample/web/formplugin-sabre-sdk-sample-form/module-protected.d.ts] (looking up the directories tree until project base directory [C:\devel\projects\srw\web_sample]). This file will not be analyzed.
11:09:10.367 ERROR: No tsconfig.json file found for [file:///C:/devel/projects/srw/web_sample/web/formplugin-sabre-sdk-sample-form/module.d.ts] (looking up the directories tree until project base directory [C:\devel\projects\srw\web_sample]). This file will not be analyzed.
11:09:10.367 DEBUG: Analyzing 18 typescript file(s) with the following configuration file C:\devel\projects\srw\web_sample\web-src\formplugin-sabre-sdk-sample-form\tsconfig.json
11:09:10.380 DEBUG: Setting 'NODE_PATH' to C:\devel\projects\srw\web_sample\node_modules
11:09:10.380 DEBUG: Starting external process `node --max-old-space-size=2048 c:\devel\projects\srw\web_sample\.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\bin\tsrunner`
11:09:12.113 ERROR: events.js:182
11:09:12.113 ERROR:       throw er; // Unhandled 'error' event
11:09:12.113 ERROR:       ^
11:09:12.114 ERROR:
11:09:12.118 ERROR: Error: write EPIPE
11:09:12.129 ERROR:     at _errnoException (util.js:1041:11)
11:09:12.129 ERROR:     at Socket._writeGeneric (net.js:758:25)
11:09:12.130 ERROR:     at Socket._write (net.js:777:8)
11:09:12.130 ERROR:     at doWrite (_stream_writable.js:385:12)
11:09:12.131 ERROR:     at writeOrBuffer (_stream_writable.js:371:5)
11:09:12.131 ERROR:     at Socket.Writable.write (_stream_writable.js:288:11)
11:09:12.132 ERROR:     at Socket.write (net.js:695:40)
11:09:12.132 ERROR:     at Object.write (c:\devel\projects\srw\web_sample\node_modules\typescript\lib\typescript.js:3950:36)
11:09:12.132 ERROR:     at Object.trace (c:\devel\projects\srw\web_sample\node_modules\typescript\lib\typescript.js:82232:49)
11:09:12.133 ERROR:     at trace (c:\devel\projects\srw\web_sample\node_modules\typescript\lib\typescript.js:24412:14)
11:09:12.229 INFO: ------------------------------------------------------------------------
11:09:12.229 INFO: EXECUTION FAILURE
11:09:12.229 INFO: ------------------------------------------------------------------------
11:09:12.230 INFO: Total time: 14.722s
11:09:12.294 INFO: Final Memory: 17M/375M
11:09:12.295 INFO: ------------------------------------------------------------------------
11:09:12.295 ERROR: Error during SonarQube Scanner execution
11:09:12.296 ERROR: Failed to run external process `node --max-old-space-size=2048 c:\devel\projects\srw\web_sample\.scannerwork\sonarts-bundle\node_modules\tslint-sonarts\bin\tsrunner`. Run with -X for more information
11:09:12.296 ERROR: Caused by: com.google.gson.stream.MalformedJsonException: Expected value at line 1 column 1 path $
11:09:12.296 ERROR: Caused by: Expected value at line 1 column 1 path $
11:09:12.297 ERROR:
11:09:12.297 ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

**Expected behavior**

Sonar scan should pass even if traceResolution tsconfig option is set to true.

### PR DESCRIPTION
**Pull request by andrea-guarino-sonarsource**
Fixes #688

### CODE REVIEW

File: sonarts-core/src/utils/parser.ts [hunk 1]
```diff
@@ -69,7 +69,9 @@ export function parseFile(filename: string): { sourceFile: ts.SourceFile; progra
 export function createProgram(configFile: string): ts.Program {
   const { options, files } = parseTsConfig(configFile);
   const host = ts.createCompilerHost(options, true);
-  return ts.createProgram(files, options, host);
+  // make sure traceResolution is disabled because it generates a lot of content on stdout
+  const optionsWithoutTrace = Object.assign(options, { traceResolution: false });
```
Comment (m-g-sonar) [inline sonarts-core/src/utils/parser.ts]: Don't you have a way to unit test directly this?

The IT is pretty cool and a nice addition (which I managed to use correctly... bug was on the other side of the keyboard), but I wonder if it wouldn't be also good to have a dedicated unit test just checking that we are never calling createProgram() with options having `traceResolution` being true.

Comment (andrea-guarino-sonarsource) [reply sonarts-core/src/utils/parser.ts]: I agree: I think I will move those two added lines inside `parseTsConfig` function and will unit test it. Thanks!
