### PR TITLE
Exclude files having unrecognized line separators

### LINKED ISSUE #687: IllegalArgumentException on Unicode Character 'LINE SEPARATOR'
When a valid [Unicode Character 'LINE SEPARATOR' (U+2028)](https://www.fileformat.info/info/unicode/char/2028/index.htm) is present in a file which is analyzed, the analysis crashes. After I removed the character, the analysis passed successfully.

It might be the root cause of #594.

**SonarTS version:** 1.7 (build 2893)
**Node.js version:** I don't think it's relevant
**TypeScript version:** I don't think it's relevant

**SonarQube version:** 6.7.3.38370
**SonarLint version and used IDE:** I don't think it's relevant
**TSLint version:** I don't think it's relevant

**Reproducer** 

Just put somewhere: [Unicode Character 'LINE SEPARATOR' (U+2028)](https://www.fileformat.info/info/unicode/char/2028/index.htm).  We had it in a tsx file (TypeScript+React).

**Logs**

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: Unable to highlight file web/src/pages/PartnerPage.tsx
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:97)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:37)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.saveHighlights(ExternalTypescriptSensor.java:284)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.analyze(ExternalTypescriptSensor.java:140)
	at org.sonar.plugin.typescript.ExternalTypescriptSensor.execute(ExternalTypescriptSensor.java:109)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalArgumentException: 65 is not a valid line offset for pointer. File web/src/pages/PartnerPage.tsx has 10 character(s) at line 251
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:312)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:246)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:261)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:95)
	... 36 more
```

**Expected behavior**

Not failing?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #687

### CODE REVIEW

File: sonarts-sq-plugin/sonar-typescript-plugin/src/test/java/org/sonar/plugin/typescript/ContextualSensorTest.java [hunk 1]
```diff
@@ -78,13 +79,14 @@ public void should_save_issues() throws Exception {
...
   }
 
-
   @Test
   public void should_not_execute_if_not_file_uri() throws Exception {
     SensorContextTester sensorContext = SensorContextTester.create(BASE_DIR);
 
     DefaultInputFile testInputFile = new TestInputFileBuilder("moduleKey", "foo/file.ts")
       .setLanguage(TypeScriptLanguage.KEY)
+      .setContents("function foo() { return `hello`; }\n")
```
Comment (andrea-guarino-sonarsource) [inline sonarts-sq-plugin/sonar-typescript-plugin/src/test/java/org/sonar/plugin/typescript/ContextualSensorTest.java]: is this change related to your PR?

**Review by andrea-guarino-sonarsource — APPROVED** [review]
LGTM, just a minor comment
