### PR TITLE
fix areEquivalent for jsx

### LINKED ISSUE #172: "areEquivalent" util doesn't work properly for jsx
For example, the `no-all-duplicated-branches` rule raises error on the following code:
```typescript
function render() {
  if (a) {
    return <p>foo</p>;
  } else {
    return <p>bar</p>;
  }
}
```

But two branches of code are obviously different.

### PR DESCRIPTION
**Pull request by stas-vilchik**
fixes #172

### CODE REVIEW

File: src/utils/areEquivalent.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ const COMPARED_BY_TEXT = new Set([
   ts.SyntaxKind.TemplateHead,
   ts.SyntaxKind.TemplateMiddle,
   ts.SyntaxKind.TemplateTail,
+  ts.SyntaxKind.JsxText,
```
Comment (stas-vilchik) [inline src/utils/areEquivalent.ts]: this is the main change
